### ISSUE TITLE
Оповещения пользователей о новых голосованиях

### ISSUE THREAD

**Issue by kazeevn** [alexsyrom/dgap_voting#34]
Предложить пользователю подписаться на старт новых голосований, где он входит в ЦА.

**Comment by alexsyrom** [comment]
![killit](https://cloud.githubusercontent.com/assets/4150868/6505861/54677a96-c357-11e4-8b92-97682c660406.png)
При создании голосования в админке есть эти поля. Более того, время последней рассылки нужно заполнить. Это нужно исправить

**Comment by paulin-mipt** [comment]
Исправлено
