### ISSUE TITLE
Дорусифицировать админку

### ISSUE THREAD

**Issue by paulin-mipt** [alexsyrom/dgap_voting#43]
Убрать перлы типа "Выберите poll для изменения".

**Comment by alexsyrom** [comment]
![psa_admin](https://cloud.githubusercontent.com/assets/4150868/6127758/ac7fede6-b13f-11e4-9467-e2d21587be0f.png)
Тогда придётся заниматься локализацией используемых django-приложений. Я думаю, в русификации нет необходимости.

**Comment by paulin-mipt** [comment]
Необходимости нет много в чём, ~а ты купи слона!~ но если этой админкой будет кто-то пользоваться, то по-хорошему всё должно быть на одном языке, хоть бы даже и английском.
Другой вопрос, что эта задача далеко не первостепенная.
