### ISSUE TITLE
Указывать часовой пояс в датах голосования

### ISSUE THREAD

**Issue by kazeevn** [alexsyrom/dgap_voting#49]

**Comment by paulin-mipt** [comment]
В pdf?
На сайте?
Всегда и везде?

**Comment by kazeevn** [comment]
Напоминание про часовой пояс пригодится на каникулах, когда люди уезжают домой. То есть, нужно на сайте. А какие ты видишь проблемы с тем, чтобы писать всегда и везде?

**Comment by paulin-mipt** [comment]
Технически проблем никаких. Просто перед добавлением дополнительной информации хочется понимать, кому и зачем она нужна, чтобы информации в один прекрасный день не стало слишком много.

**Comment by alexsyrom** [comment]
На сайте есть свои часы, которые отражают время на сервере.

**Comment by kazeevn** [comment]
Про много информации согласен. На плакатах будет явно лишним. Предлагаю оставить в поле "конец" на сайте.

**Comment by alexsyrom** [comment]
Я понимаю смысл указания часового пояса в датах, которые будут фигурировать в рассылках. А вот смысла в указании часового пояса на сайте я пока не вижу, ведь, как я уже заметил, на сайте присутствуют часы, по которым можно узнать время на сервере, относительно которого и указываются сроки голосований.

**Comment by kazeevn** [comment]
ОК, согласен. Про сайт - я с трудом представляю себе человека, который зайдёт, посмотрит время окончания и потом вернётся.
