### ISSUE TITLE
Don't use hardcoded urls

### ISSUE THREAD

**Issue by kazeevn** [alexsyrom/dgap_voting#50]
That's a laborious, non-scalable and error-prone strategy. Use revrse(). https://docs.djangoproject.com/en/1.7/topics/http/urls/#reverse-resolution-of-urls

1. https://github.com/alexsyrom/dgap_voting/commit/88f493df1c4d7d7f772e9fdfc27a2ccb87ea81c9#diff-6a981fa2215c848cd8e2a8539d741951R174
2. https://github.com/alexsyrom/dgap_voting/commit/0690776cff5754d0611f9d7ce7d011c0ffb97b94#diff-20e758ebb60d1755ccf454fed46eb264R16
3. https://github.com/alexsyrom/dgap_voting/commit/6d62deab5721bf18a6867a6c62a804e927ec97d0#diff-6a981fa2215c848cd8e2a8539d741951R155

**Comment by paulin-mipt** [comment]
1 и 2 - исправлено, а что не так с третьей ссылкой? 
Кажется, это вполне адекватная запись для адреса template.

**Comment by kazeevn** [comment]
3 - ты права, я был невнимателен.
