### ISSUE TITLE
Пустая главная страница и незарегистрированных пользователей

### ISSUE THREAD

**Issue by kazeevn** [alexsyrom/dgap_voting#72]
Она их немного смущает, было бы хорошо сверху поставить большую цветную кнопку "войти".

**Comment by alexsyrom** [comment]
Она не пустая, на ней завершённые голосования. Просто их пока нет.

**Comment by alexsyrom** [comment]
А нет, есть. Голосование "Teset"

**Comment by kazeevn** [comment]
Да (но его скоро не будет). Если это просто, не мог бы ты добавить большую цветную кнопку "войти" над результатами. (Если сложно, давай отложим)

**Comment by alexsyrom** [comment]
Добавил большую синюю ссылку на главную
