### ISSUE TITLE
Убрать кнопки "вход" и "регистрация", оставить только phystech.edu

### ISSUE THREAD

**Issue by kazeevn** [alexsyrom/dgap_voting#74]
Люди путаются - пытаются сделать аккаунт с логином и паролем. К чему это, если можно просто оставить только "войти через phystech.edu"?

**Comment by alexsyrom** [comment]
ОК, я уберу ссылки на вход через логин-пароль и регистрацию. Функциональность останется, но её не будет видно обычным пользователям
